services:
  - type: web
    name: fmscouter
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT
    envVars:
      - key: FM_HOST
        value: "0.0.0.0"
      - key: FM_DEBUG
        value: "false"
      - key: FM_AUTH_USER
        sync: false
      - key: FM_AUTH_PASSWORD
        sync: false
      - key: FM_SECRET_KEY
        generateValue: true
